# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8f4d533131befd76c6d406179f2904923c2f3486411ce7ab3ec2e13bbee7a92890bd00bbcf3c6a0e92b54bdb51212b8de500c4d76c7a6ca4ab4ebffbb77831

test:
  secret_key_base: 4f542fe68f72481c08ab0dd56d2a68a15d48421fa1ba6ec1b11c95835cbc7fa1c336b98edc7d8e12b62832aab7bff2149e1cc9be7a5dc7230ee1650715b31dca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
